<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Envo</name>
   <tag></tag>
   <elementGuidId>c97a342e-8e8c-4326-98a1-e9cb1202b5b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul > a.font-text.pointer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/ul/li[2]/div/ul/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6fd63b56-36ec-4905-8cc6-4e868d946c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-text pointer</value>
      <webElementGuid>02ea2a0a-8169-476a-8c26-c5946759cd59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/envios</value>
      <webElementGuid>d83edea8-8d47-4646-b46f-ca35969eedf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Envío</value>
      <webElementGuid>efa73e4a-ea59-443d-a17c-9cbe07c3189a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;page-container&quot;]/div[1]/div[@class=&quot;sidebar&quot;]/ul[@class=&quot;lateral-menu&quot;]/li[2]/div[@class=&quot;font-text&quot;]/ul[1]/a[@class=&quot;font-text pointer&quot;]</value>
      <webElementGuid>de9ee808-a0ca-417c-8191-b6c7b36ef6bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8536a499-dcce-417b-9689-0eb90ed194e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-text pointer</value>
      <webElementGuid>3a903c53-c6fa-4016-946e-e7e7636310a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/envios</value>
      <webElementGuid>2d465554-a597-4308-bc5d-a3b58af726ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Envío</value>
      <webElementGuid>63fb6c81-40b4-4675-830a-979fc1e5447c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;page-container&quot;]/div[1]/div[@class=&quot;sidebar&quot;]/ul[@class=&quot;lateral-menu&quot;]/li[2]/div[@class=&quot;font-text&quot;]/ul[1]/a[@class=&quot;font-text pointer&quot;]</value>
      <webElementGuid>4a586252-2ac2-4f85-976f-2bdfdb6c90cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e3a0719c-b6b3-4482-99cf-494dc1259882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-text pointer</value>
      <webElementGuid>7902f5ab-dc24-43e6-bad5-2952f8a89495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/envios</value>
      <webElementGuid>e4633cd5-4c58-4058-a057-fbf0382480af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Envío</value>
      <webElementGuid>1c65adaf-3fc8-4fb6-bfea-f0ebb65a749f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;page-container&quot;]/div[1]/div[@class=&quot;sidebar&quot;]/ul[@class=&quot;lateral-menu&quot;]/li[2]/div[@class=&quot;font-text&quot;]/ul[1]/a[@class=&quot;font-text pointer&quot;]</value>
      <webElementGuid>cf2021f8-fc83-4a97-8dc7-0bcefba924fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/ul/li[2]/div/ul/a</value>
      <webElementGuid>c9a70178-288c-4037-a59a-b5015fa104a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Envío')]</value>
      <webElementGuid>eb5b25c3-76a3-42a4-b968-249b2d890df4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[1]</value>
      <webElementGuid>22626a8e-a608-4e07-93c8-b436f3fa9f80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resultado'])[1]/preceding::a[1]</value>
      <webElementGuid>53b405e4-8c3a-4378-8fc1-7758e67e5ae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consulta'])[1]/preceding::a[2]</value>
      <webElementGuid>c8eefb99-54d3-4568-bc2e-ae5b40940e35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Envío']/parent::*</value>
      <webElementGuid>90337164-c914-4ad0-a5af-ac9e8104c9fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/envios')]</value>
      <webElementGuid>acd6caaa-815a-442e-9187-93e5a119c7e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/a</value>
      <webElementGuid>4b30b60e-a0d3-4ff6-9f89-0cf471a338d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/envios' and (text() = 'Envío' or . = 'Envío')]</value>
      <webElementGuid>d7fc2dbd-da93-4c28-94b3-ea6dd16c8e3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
