<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Tcnica de InmunohistoqumicaTipo-- Selec_da30ee</name>
   <tag></tag>
   <elementGuidId>3951a692-be60-41fb-81c5-d8c984b6dbc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/form/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9401c2d4-adf5-45f7-8582-7cab9b2bd8d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Técnica de InmunohistoquímicaTipo:-- Seleccione un tipo --ManualAut. VentanaAut. DAKO / AgilentAut. LEICAOtrosAnticuerpo PrimarioClon:-- Seleccione un clon --SP1EP16F11EP220OtroMarca:-- Seleccione una marca --DAKO - AGILENTVENTANALEICACELLMARQUEBIOSBBIOGENEXVECTORDilución:-- Seleccione una dilución --1:501:1001:2001:500OtroTiempo de incubación:-- Seleccione un tiempo --15 min30 min60 minOvernightOtroTemperatura:-- Seleccione la temperatura --0°C5°C10°C15°C20°C25°C30°C35°C40°C45°C50°C55°C60°C65°C70°C75°C80°C85°C90°C95°C100°CRecuperación AntigénicaDispositivo:-- Seleccione un dispositivo --AutomatizadoMicroondasOlla a presiónBaño térmicoOtroBuffer:Tiempo:-- Seleccione un tiempo --15 min30 min60 minOvernightOtroTemperatura:-- Seleccione la temperatura --0°C5°C10°C15°C20°C25°C30°C35°C40°C45°C50°C55°C60°C65°C70°C75°C80°C85°C90°C95°C100°C</value>
      <webElementGuid>a7c25ae4-76fe-4abb-ae8e-a6fe79cba1d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;form-container&quot;]/form[1]/div[2]</value>
      <webElementGuid>8d3780aa-bc2f-4145-8b52-196a60e7551d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2c453a24-e73a-47dd-95bb-48d75387928f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Técnica de InmunohistoquímicaTipo:-- Seleccione un tipo --ManualAut. VentanaAut. DAKO / AgilentAut. LEICAOtrosAnticuerpo PrimarioClon:-- Seleccione un clon --SP1EP16F11EP220OtroMarca:-- Seleccione una marca --DAKO - AGILENTVENTANALEICACELLMARQUEBIOSBBIOGENEXVECTORDilución:-- Seleccione una dilución --1:501:1001:2001:500OtroTiempo de incubación:-- Seleccione un tiempo --15 min30 min60 minOvernightOtroTemperatura:-- Seleccione la temperatura --0°C5°C10°C15°C20°C25°C30°C35°C40°C45°C50°C55°C60°C65°C70°C75°C80°C85°C90°C95°C100°CRecuperación AntigénicaDispositivo:-- Seleccione un dispositivo --AutomatizadoMicroondasOlla a presiónBaño térmicoOtroBuffer:Tiempo:-- Seleccione un tiempo --15 min30 min60 minOvernightOtroTemperatura:-- Seleccione la temperatura --0°C5°C10°C15°C20°C25°C30°C35°C40°C45°C50°C55°C60°C65°C70°C75°C80°C85°C90°C95°C100°C</value>
      <webElementGuid>e5a3da7e-ac2d-459a-b4d2-805651239877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;form-container&quot;]/form[1]/div[2]</value>
      <webElementGuid>d5f70d34-b25b-42b4-a3c5-10c19ef9ccca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/form/div[2]</value>
      <webElementGuid>41ff9abf-083c-4a88-a63a-25269a33c333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enviar'])[1]/following::div[1]</value>
      <webElementGuid>9567b127-f7fe-4889-9928-3df04bd0851b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]</value>
      <webElementGuid>91cf21bf-8cc4-4b40-999a-b3ef2dd1a159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Técnica de InmunohistoquímicaTipo:-- Seleccione un tipo --ManualAut. VentanaAut. DAKO / AgilentAut. LEICAOtrosAnticuerpo PrimarioClon:-- Seleccione un clon --SP1EP16F11EP220OtroMarca:-- Seleccione una marca --DAKO - AGILENTVENTANALEICACELLMARQUEBIOSBBIOGENEXVECTORDilución:-- Seleccione una dilución --1:501:1001:2001:500OtroTiempo de incubación:-- Seleccione un tiempo --15 min30 min60 minOvernightOtroTemperatura:-- Seleccione la temperatura --0°C5°C10°C15°C20°C25°C30°C35°C40°C45°C50°C55°C60°C65°C70°C75°C80°C85°C90°C95°C100°CRecuperación AntigénicaDispositivo:-- Seleccione un dispositivo --AutomatizadoMicroondasOlla a presiónBaño térmicoOtroBuffer:Tiempo:-- Seleccione un tiempo --15 min30 min60 minOvernightOtroTemperatura:-- Seleccione la temperatura --0°C5°C10°C15°C20°C25°C30°C35°C40°C45°C50°C55°C60°C65°C70°C75°C80°C85°C90°C95°C100°C' or . = 'Técnica de InmunohistoquímicaTipo:-- Seleccione un tipo --ManualAut. VentanaAut. DAKO / AgilentAut. LEICAOtrosAnticuerpo PrimarioClon:-- Seleccione un clon --SP1EP16F11EP220OtroMarca:-- Seleccione una marca --DAKO - AGILENTVENTANALEICACELLMARQUEBIOSBBIOGENEXVECTORDilución:-- Seleccione una dilución --1:501:1001:2001:500OtroTiempo de incubación:-- Seleccione un tiempo --15 min30 min60 minOvernightOtroTemperatura:-- Seleccione la temperatura --0°C5°C10°C15°C20°C25°C30°C35°C40°C45°C50°C55°C60°C65°C70°C75°C80°C85°C90°C95°C100°CRecuperación AntigénicaDispositivo:-- Seleccione un dispositivo --AutomatizadoMicroondasOlla a presiónBaño térmicoOtroBuffer:Tiempo:-- Seleccione un tiempo --15 min30 min60 minOvernightOtroTemperatura:-- Seleccione la temperatura --0°C5°C10°C15°C20°C25°C30°C35°C40°C45°C50°C55°C60°C65°C70°C75°C80°C85°C90°C95°C100°C')]</value>
      <webElementGuid>e90326f6-f49a-4f3b-ae54-6bd4ac7ddbd2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
