<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Seleccione una imagen_img-protocol pointer</name>
   <tag></tag>
   <elementGuidId>08da88fe-b3aa-44e9-8f5f-3f47ff18e052</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.img-protocol.pointer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>09e51c6b-b8c0-42e3-9ac0-482ee521f2d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-protocol pointer</value>
      <webElementGuid>9dcb3838-dadc-4f1d-82df-79f3f176da3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>../../img/RE.png</value>
      <webElementGuid>017c10aa-c0c0-4ead-8a68-f7b4fa572873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../img/RE.png</value>
      <webElementGuid>a004c787-c8ce-427a-b3cd-e9fd8ce27cf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[2]/div[@class=&quot;central-screen&quot;]/div[@class=&quot;img-container&quot;]/img[@class=&quot;img-protocol pointer&quot;]</value>
      <webElementGuid>03e5ff72-d77c-4159-8c74-428df73927fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ccc10dcc-245f-4a1c-b974-af4cdfb1ecd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-protocol pointer</value>
      <webElementGuid>5c40c5da-e62e-495d-9d73-6b341b115f23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>../../img/RE.png</value>
      <webElementGuid>0c29d736-cf89-41c2-a6c2-66153de717aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../img/RE.png</value>
      <webElementGuid>c81f95a3-ce50-4db8-8f5d-e6eab8f95795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[2]/div[@class=&quot;central-screen&quot;]/div[@class=&quot;img-container&quot;]/img[@class=&quot;img-protocol pointer&quot;]</value>
      <webElementGuid>42dbeaef-5b67-49b3-990f-5fd1ff20fce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>63503283-481e-4c29-9efb-47479765c209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-protocol pointer</value>
      <webElementGuid>1e6c23b6-647a-49c9-a4d7-900d4e259afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>../../img/RE.png</value>
      <webElementGuid>e07bfc04-6900-4269-a276-456ddb7bc7da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../img/RE.png</value>
      <webElementGuid>e7f0aac1-2cec-4b29-8d02-58bf388fb9a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[2]/div[@class=&quot;central-screen&quot;]/div[@class=&quot;img-container&quot;]/img[@class=&quot;img-protocol pointer&quot;]</value>
      <webElementGuid>ab4f77fc-524e-4717-8591-e5a284960832</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/img</value>
      <webElementGuid>0cf47879-fcd1-4bd2-a600-1b498996e0a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='../../img/RE.png']</value>
      <webElementGuid>30422f55-db23-4cb6-ad24-85adee8647b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>0b80fb78-d089-4f8d-ab60-9a80d7a5656b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = '../../img/RE.png' and @src = '../../img/RE.png']</value>
      <webElementGuid>56d5ce51-57a5-4078-8f55-270582197bf2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
