<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Producto_chromogenProduct</name>
   <tag></tag>
   <elementGuidId>faf226c1-a0ae-4900-9c4e-c310608380ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='chromogenProduct']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#chromogenProduct</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b75c9a22-ef24-491e-abd8-48bafeaf0af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fdfff56e-5192-40c5-a123-1ea2e95c39f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chromogenProduct</value>
      <webElementGuid>7d76acae-d0ea-4726-b6ea-d83e237e5c48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chromogenProduct</value>
      <webElementGuid>54be4a91-d194-48a6-b985-381e8ad91022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingrese producto</value>
      <webElementGuid>98f6e928-edad-40fb-aeea-ad534711c0b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>4321</value>
      <webElementGuid>3c6cfbc6-a736-4077-990e-44655bdfbf59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chromogenProduct&quot;)</value>
      <webElementGuid>946bbff6-5681-4cc4-9059-97e0f2338b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>869d9981-709c-47f6-8b3d-1fffb2e321a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e92c794f-d00a-4c98-ac3f-3d6b94aee0c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chromogenProduct</value>
      <webElementGuid>d32f5773-e600-420c-9a8e-a9faed583605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chromogenProduct</value>
      <webElementGuid>cb2422f5-4ed3-4088-9d2d-e8ef246d9b4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingrese producto</value>
      <webElementGuid>b2ace992-eaab-4590-b872-862dcbd82b96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chromogenProduct&quot;)</value>
      <webElementGuid>f828c206-ee4e-4613-bf11-ad694eac9117</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='chromogenProduct']</value>
      <webElementGuid>3c4d4a2e-d8a0-4db7-8df5-1bbd3d041a19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/form/div[3]/div[6]/input</value>
      <webElementGuid>89f871cc-8edb-496d-a395-1dde54a0f59f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>751dac9f-767f-455f-80c5-e9fcc324db0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'chromogenProduct' and @name = 'chromogenProduct' and @placeholder = 'Ingrese producto']</value>
      <webElementGuid>5866e46a-3c73-4b98-a4db-2ffcf9e03495</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
