<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Buffer_antigenicRetrievalBuffer</name>
   <tag></tag>
   <elementGuidId>4539b5a8-a2cc-4620-b8ca-f41a0455fca5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='antigenicRetrievalBuffer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#antigenicRetrievalBuffer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3cc32dc5-21e8-42dc-b35f-8d213acf10cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b6cfd63f-373d-47af-914b-90acaa02cb1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>antigenicRetrievalBuffer</value>
      <webElementGuid>cb75744a-cb32-459c-8096-1ab613aba505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>antigenicRetrievalBuffer</value>
      <webElementGuid>a8fb49ed-2fb3-4583-a7c0-c97c48b5466a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingrese buffer</value>
      <webElementGuid>dda6fe69-29b0-4e71-9de8-f718e02cdcbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1234</value>
      <webElementGuid>21346d52-5d3c-4843-9879-abf53846012e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;antigenicRetrievalBuffer&quot;)</value>
      <webElementGuid>47820237-374a-4ce8-a856-4e5d279c14a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f0e39a4-6d5a-415a-bfd6-b66347eaed8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d7bfb2d6-cb22-48ab-a4fd-ffad875ce9b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>antigenicRetrievalBuffer</value>
      <webElementGuid>4256baf3-564b-4eeb-a256-f741b7a7e5db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>antigenicRetrievalBuffer</value>
      <webElementGuid>bffda18f-3e86-46a7-8306-b531c6abbddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingrese buffer</value>
      <webElementGuid>5b4b752c-8515-4e35-ba41-4b95d7b5a040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;antigenicRetrievalBuffer&quot;)</value>
      <webElementGuid>a1155069-9cba-4244-bc41-a4fba38857ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='antigenicRetrievalBuffer']</value>
      <webElementGuid>0738fa62-5bcf-4726-937b-501a749fed59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/form/div[2]/div[8]/input</value>
      <webElementGuid>f59ef6d8-17c5-4d73-a6fd-fd68904bc2a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>818e64b8-e1cc-4701-bb29-cf7560c6de24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'antigenicRetrievalBuffer' and @name = 'antigenicRetrievalBuffer' and @placeholder = 'Ingrese buffer']</value>
      <webElementGuid>14c9efe8-08de-4cc8-9aca-53b25dde9f97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
