<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Producto_visualizationSystemProduct</name>
   <tag></tag>
   <elementGuidId>6c3b6f07-4408-4465-80e2-3070e77f0e4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='visualizationSystemProduct']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#visualizationSystemProduct</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>edaa6f0b-464f-4991-850c-e4b482c24148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6c1bb54f-7a2a-4f7f-877a-e3be1fa01243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>visualizationSystemProduct</value>
      <webElementGuid>aab31ce4-7a29-451e-b43b-613d60d0b58b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>visualizationSystemProduct</value>
      <webElementGuid>cb1bd186-fb0c-4f7d-93fb-9c3de70cfad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingrese producto</value>
      <webElementGuid>aa1b4753-6771-4899-9bac-109f85c8e621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>mmmm</value>
      <webElementGuid>9beee2a1-c415-4944-8cc9-ac0b19748e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;visualizationSystemProduct&quot;)</value>
      <webElementGuid>2fe60adc-1e47-4655-af03-a9f7c9d2237b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d690c5a-7cd5-4fd2-a119-a68a65f9f8e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d6026774-4f56-4176-87bd-3c0f9105616b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>visualizationSystemProduct</value>
      <webElementGuid>6ad8ccfe-ce56-4781-9e4b-f48c842ba9dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>visualizationSystemProduct</value>
      <webElementGuid>f27c83dc-c535-4590-8867-1afbde426a0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingrese producto</value>
      <webElementGuid>89f67dc0-c8bf-47d3-a5e5-66ab4b735a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;visualizationSystemProduct&quot;)</value>
      <webElementGuid>74bded33-ed43-4403-85fc-3549ef0b67ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='visualizationSystemProduct']</value>
      <webElementGuid>0a5df3cc-d957-46f9-b87c-25ed2d0d07b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/form/div[3]/div[2]/input</value>
      <webElementGuid>50a44423-3b7d-490d-9d10-a637309045cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>ca50ac1d-950f-4266-9fdf-c1a9803eca52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'visualizationSystemProduct' and @name = 'visualizationSystemProduct' and @placeholder = 'Ingrese producto']</value>
      <webElementGuid>f86d1621-ec17-4545-925f-41cfc3ade3e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
