<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Seleccione la temperatura --0C5C1_fedc78_1</name>
   <tag></tag>
   <elementGuidId>190d4e5d-8ae1-465c-a765-8263901b778a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='antigenicRetrievalTemperature']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#antigenicRetrievalTemperature</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>245ffefd-deca-47d2-8844-f86f96954315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>dcce6d40-141a-48dd-ba26-554491eba3f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>antigenicRetrievalTemperature</value>
      <webElementGuid>07ad1963-59df-452d-8cb8-a4a9f4454357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>antigenicRetrievalTemperature</value>
      <webElementGuid>345c5623-1052-4d91-9e32-6eb00b0dbd92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Seleccione la temperatura --0°C5°C10°C15°C20°C25°C30°C35°C40°C45°C50°C55°C60°C65°C70°C75°C80°C85°C90°C95°C100°C</value>
      <webElementGuid>9ce810b5-852a-4d76-9906-78614bf4e008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;antigenicRetrievalTemperature&quot;)</value>
      <webElementGuid>5b4cab77-da50-4f41-a56d-f124c9afeaf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>db35a8aa-73b0-4397-955d-28c19bb0345a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>279ec857-d9e8-4c67-83fc-2839a76ecf67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>antigenicRetrievalTemperature</value>
      <webElementGuid>a57e150a-6e60-4de8-87a7-109cb97734ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>antigenicRetrievalTemperature</value>
      <webElementGuid>77c0f4c3-ce44-44b1-8776-787ef6f2a36b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Seleccione la temperatura --0°C5°C10°C15°C20°C25°C30°C35°C40°C45°C50°C55°C60°C65°C70°C75°C80°C85°C90°C95°C100°C</value>
      <webElementGuid>e9c34561-551c-46cc-8527-89422d839913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;antigenicRetrievalTemperature&quot;)</value>
      <webElementGuid>ae3f2a21-0a9e-41df-ac32-2bcae2156e78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='antigenicRetrievalTemperature']</value>
      <webElementGuid>158800f7-0c3a-41d6-b827-556fc51679db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/form/div[2]/div[10]/select</value>
      <webElementGuid>aa778892-3a98-452a-935e-3d5b52200883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temperatura:'])[2]/following::select[1]</value>
      <webElementGuid>55947ef5-a1dc-477c-b476-294cf84ab3ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiempo:'])[1]/following::select[2]</value>
      <webElementGuid>e1ae19f3-221a-4270-8800-66554debdda2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sistema de Visualización'])[1]/preceding::select[1]</value>
      <webElementGuid>bf46ccd4-5fd2-45ef-95ee-3c8d7a79ff10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marca:'])[2]/preceding::select[1]</value>
      <webElementGuid>557aafdb-1d5f-45c2-83ad-198e11f69580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/select</value>
      <webElementGuid>e272c6ef-470e-4030-b82c-e3298c94cef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'antigenicRetrievalTemperature' and @name = 'antigenicRetrievalTemperature' and (text() = '-- Seleccione la temperatura --0°C5°C10°C15°C20°C25°C30°C35°C40°C45°C50°C55°C60°C65°C70°C75°C80°C85°C90°C95°C100°C' or . = '-- Seleccione la temperatura --0°C5°C10°C15°C20°C25°C30°C35°C40°C45°C50°C55°C60°C65°C70°C75°C80°C85°C90°C95°C100°C')]</value>
      <webElementGuid>d251c550-2ae7-4320-9bb5-8f254493b10a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
