<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Seleccione una marca --DAKO - AGI_de3eda_1_2</name>
   <tag></tag>
   <elementGuidId>160c0265-42ff-4b14-a4bd-8db7698ac0f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='chromogenBrand']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#chromogenBrand</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7a61d11a-d3d9-4a64-b125-0688432849dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>e311d415-a5ca-47ea-8d8f-6bbdf53cba24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chromogenBrand</value>
      <webElementGuid>8b07c1cb-1dc9-466c-b2ee-2c65545903e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chromogenBrand</value>
      <webElementGuid>749b5836-52cc-4aa3-855f-5c0c413bc76a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Seleccione una marca --DAKO - AGILENTVENTANALEICACELLMARQUEBIOSBBIOGENEXVECTOR</value>
      <webElementGuid>3450f21e-1729-4614-a98c-f031cd0fcba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chromogenBrand&quot;)</value>
      <webElementGuid>44ccf2d7-1c24-4989-88e2-08a1c8655d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3bd901bf-da5b-4c7c-aac8-7f3ea27b49a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>2905026d-8584-42c8-95ac-850212676485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chromogenBrand</value>
      <webElementGuid>c71cc98b-c01b-4e2b-a0d9-053f6a31b1d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chromogenBrand</value>
      <webElementGuid>1a26dfac-adb6-4534-b3ac-7f2b6583533d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Seleccione una marca --DAKO - AGILENTVENTANALEICACELLMARQUEBIOSBBIOGENEXVECTOR</value>
      <webElementGuid>491214be-77db-40eb-bd82-fc48e4f05b5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chromogenBrand&quot;)</value>
      <webElementGuid>e29333b1-614e-4e19-8e02-1078425f96c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='chromogenBrand']</value>
      <webElementGuid>099f6fae-5beb-4c70-a63f-65049572953c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/form/div[3]/div[5]/select</value>
      <webElementGuid>1f16ac1f-43a8-4223-a87c-3537c71d562b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marca:'])[3]/following::select[1]</value>
      <webElementGuid>fa93d0d4-2ac1-4760-bd7c-92e9e242bcdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cromógeno'])[1]/following::select[1]</value>
      <webElementGuid>788e1dd5-a991-4b3c-b160-122a5065c476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Producto:'])[2]/preceding::select[1]</value>
      <webElementGuid>8d9868ed-c59a-4b3e-8090-a0bbfb25ce7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiempo de incubación:'])[3]/preceding::select[1]</value>
      <webElementGuid>da4c5020-fad0-4513-8708-b72f0232047f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[5]/select</value>
      <webElementGuid>4e7ba259-d6af-4e11-8ccd-253b50b77398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'chromogenBrand' and @name = 'chromogenBrand' and (text() = '-- Seleccione una marca --DAKO - AGILENTVENTANALEICACELLMARQUEBIOSBBIOGENEXVECTOR' or . = '-- Seleccione una marca --DAKO - AGILENTVENTANALEICACELLMARQUEBIOSBBIOGENEXVECTOR')]</value>
      <webElementGuid>cc9fbf94-8e3d-4163-9fdd-a3ed93dfbd17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
