<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Seleccione una dilucin --15011001_612565</name>
   <tag></tag>
   <elementGuidId>05cef73d-3302-4fa7-bf1b-2842586c08c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#primaryAntigenDilution</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='primaryAntigenDilution']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>edeb12ed-178b-42c2-adc0-756c12b5a21e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>760ec2b4-1113-4ff0-a075-707fd3878aa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>primaryAntigenDilution</value>
      <webElementGuid>3bbb06b3-2d96-4205-9e65-5775042f1063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>primaryAntigenDilution</value>
      <webElementGuid>326191b2-c459-450e-89e3-270aa36857f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Seleccione una dilución --1:501:1001:2001:500Otro</value>
      <webElementGuid>af95ab68-d2b6-4a6b-bc92-ea5929735109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;primaryAntigenDilution&quot;)</value>
      <webElementGuid>03de87ee-ff3c-47cf-9815-898e75ab62ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d5e5e4f6-66fb-4ecb-b9df-c42272aa8e2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>2569b4ca-9757-44cd-a1d7-24ccf5ddad94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>primaryAntigenDilution</value>
      <webElementGuid>fe52deab-b6bd-452e-8def-bb50e107bb21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>primaryAntigenDilution</value>
      <webElementGuid>b1d0d372-b8c2-4c6a-8a7d-b0f1511577f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Seleccione una dilución --1:501:1001:2001:500Otro</value>
      <webElementGuid>9b034f19-66c8-4201-98ef-c6d425cfcc14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;primaryAntigenDilution&quot;)</value>
      <webElementGuid>3126aa93-99da-467e-915b-abd03ba1e6db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>be8ecf1e-e6e9-4104-aac7-42a22500e6b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>8a678d9e-6757-4cec-97aa-1aa3c3d9d29a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>primaryAntigenDilution</value>
      <webElementGuid>a3380c3c-ed99-4c8d-9b1d-1ded57e0446f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>primaryAntigenDilution</value>
      <webElementGuid>188f4b27-2c56-4bb5-a496-8043df7b4514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Seleccione una dilución --1:501:1001:2001:500Otro</value>
      <webElementGuid>1f6fbd5e-75c2-4769-b0a6-9739b7856ec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;primaryAntigenDilution&quot;)</value>
      <webElementGuid>a6e4fb18-e6e6-482d-9268-558f4d14d34f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='primaryAntigenDilution']</value>
      <webElementGuid>b8cf4ddf-4f07-4ccd-bc11-d1cbe6bb9631</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/form/div[2]/div[4]/select</value>
      <webElementGuid>869ddeb5-7a16-438d-bd9b-c90dcda094fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dilución:'])[1]/following::select[1]</value>
      <webElementGuid>dd0b3104-3ff7-4fc2-86e7-c801b13af566</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marca:'])[1]/following::select[2]</value>
      <webElementGuid>9bd029ef-b1cb-4fc7-8a0f-7d2d9e20f61d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiempo de incubación:'])[1]/preceding::select[1]</value>
      <webElementGuid>621ba7e7-8f15-4bc0-9dba-343ebce4aeb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temperatura:'])[1]/preceding::select[2]</value>
      <webElementGuid>198470db-0565-4dc2-94a6-77f44214661e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/select</value>
      <webElementGuid>41619056-5e7f-482f-a11e-0f386b86c992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'primaryAntigenDilution' and @name = 'primaryAntigenDilution' and (text() = '-- Seleccione una dilución --1:501:1001:2001:500Otro' or . = '-- Seleccione una dilución --1:501:1001:2001:500Otro')]</value>
      <webElementGuid>6461b29e-69e9-4be8-b9c0-aec5744913d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
