<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Seleccione un tiempo --15 min30 m_562664</name>
   <tag></tag>
   <elementGuidId>98451ca6-19da-44ed-9623-224f252bfdc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#primaryAntigenIncubation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='primaryAntigenIncubation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7d8da35c-4275-47a7-8e6a-9248d2bea8f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>8cd550ed-8263-4294-9efb-2380b5bc5088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>primaryAntigenIncubation</value>
      <webElementGuid>b6923abc-8a11-4235-ac2a-ff3c3b90c97b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>primaryAntigenIncubation</value>
      <webElementGuid>574069b3-1559-413e-a0a1-6cbdc9ffe9cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Seleccione un tiempo --15 min30 min60 minOvernightOtro</value>
      <webElementGuid>b7c614c6-348b-4a6c-a725-e216b5f633e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;primaryAntigenIncubation&quot;)</value>
      <webElementGuid>2df83404-dff8-4f83-b26d-b43280a1f5a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a1fe428e-9222-4031-bd5d-6783132994b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>d565663e-30e9-4a12-92e1-8f12eeb060ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>primaryAntigenIncubation</value>
      <webElementGuid>8daaf730-620d-449c-af5c-8e5c7c3526bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>primaryAntigenIncubation</value>
      <webElementGuid>bbdf3f36-aa63-4103-bb08-d5c64a04c73f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Seleccione un tiempo --15 min30 min60 minOvernightOtro</value>
      <webElementGuid>6276b062-0ce2-40b5-bda6-10ec65be8c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;primaryAntigenIncubation&quot;)</value>
      <webElementGuid>190ca424-4dfc-4b70-adc9-d496e30b1191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>dfd39b73-1ff4-42af-b5b3-eb90cc438933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>90d7a815-d8f9-486e-90ab-7d612c1cc3a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>primaryAntigenIncubation</value>
      <webElementGuid>b8ab048c-2b9b-4fc1-a51a-6612e3d09bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>primaryAntigenIncubation</value>
      <webElementGuid>cddeb002-61d8-4364-bce5-5859d471b3a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Seleccione un tiempo --15 min30 min60 minOvernightOtro</value>
      <webElementGuid>0de0aadf-8a8c-4329-8865-1f9fc006070f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;primaryAntigenIncubation&quot;)</value>
      <webElementGuid>9d16f51d-01b1-4bc4-83f2-c4e3d263385c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='primaryAntigenIncubation']</value>
      <webElementGuid>03ea0d1e-e797-43b5-8b47-7ee809300a5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/form/div[2]/div[5]/select</value>
      <webElementGuid>7426014b-6fd5-4a44-84cc-92c1d122d0b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiempo de incubación:'])[1]/following::select[1]</value>
      <webElementGuid>b672567c-7600-47a6-bd48-c0a711421983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dilución:'])[1]/following::select[2]</value>
      <webElementGuid>fde9c454-0034-4a27-9e65-2105bd6be68d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temperatura:'])[1]/preceding::select[1]</value>
      <webElementGuid>b751806a-b2cb-4b6d-ab39-05ebab1183ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recuperación Antigénica'])[1]/preceding::select[2]</value>
      <webElementGuid>25b0020b-66ee-4296-aa44-764e82576cbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/select</value>
      <webElementGuid>c0c64540-86f3-453d-8473-f320a5d59d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'primaryAntigenIncubation' and @name = 'primaryAntigenIncubation' and (text() = '-- Seleccione un tiempo --15 min30 min60 minOvernightOtro' or . = '-- Seleccione un tiempo --15 min30 min60 minOvernightOtro')]</value>
      <webElementGuid>b87eb214-8b98-46dd-b753-e3a206260cfa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
