<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Seleccione un tiempo --15 min30 m_562664_1</name>
   <tag></tag>
   <elementGuidId>71b37428-1eac-4915-8f3e-2925233c6b60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chromogenIncubation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='chromogenIncubation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>67d3d4ff-ce5f-4efe-9c28-e80ba233b38a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>7ffbbbf5-5553-43d0-9549-f050544e6a62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chromogenIncubation</value>
      <webElementGuid>a5d71653-cb69-437a-8f9a-8d0471a3bd76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chromogenIncubation</value>
      <webElementGuid>3871f0e0-c1be-4640-b574-a8de891c689e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Seleccione un tiempo --15 min30 min60 minOvernightOtro</value>
      <webElementGuid>b3c202ec-0663-4c3f-b04f-0e169e439ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chromogenIncubation&quot;)</value>
      <webElementGuid>33c5d1ca-f435-4340-8221-0daae4174966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2c0a97e9-c158-4dee-804f-9194d2344328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>0ba3ee17-67de-4110-b8aa-02b3df409e8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>antigenicRetrievalTime</value>
      <webElementGuid>e01dd36d-f325-4c0d-ae1e-b514f0d230b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>antigenicRetrievalTime</value>
      <webElementGuid>b6ef7a6d-0c08-42c0-b8e6-ff6306f77045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Seleccione un tiempo --15 min30 min60 minOvernightOtro</value>
      <webElementGuid>ce412850-898b-4c05-add3-0bc31b9f9a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;antigenicRetrievalTime&quot;)</value>
      <webElementGuid>98758acf-b47a-4eca-9e10-1414e24a3ec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>34b93aab-4840-456d-ba24-a3ec0e11191b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>d97a50fc-64ef-41bf-820b-0195095be494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>antigenicRetrievalTime</value>
      <webElementGuid>7d5c03d4-3995-42ea-983f-773f6f3471e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>antigenicRetrievalTime</value>
      <webElementGuid>e68122b8-9cd0-4606-bed3-91173a87a441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Seleccione un tiempo --15 min30 min60 minOvernightOtro</value>
      <webElementGuid>f635954d-7514-4b27-b4e4-971209996767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;antigenicRetrievalTime&quot;)</value>
      <webElementGuid>d7f12f3a-c2a8-4798-b72d-a553cc3630c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='chromogenIncubation']</value>
      <webElementGuid>f5635d89-69ab-4224-b0c3-6e814d070702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/form/div[3]/div[7]/select</value>
      <webElementGuid>247b75f2-37dd-4f04-9cea-ae9d8319d4ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiempo de incubación:'])[3]/following::select[1]</value>
      <webElementGuid>69957606-4a14-42ef-8964-75671c7007dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Producto:'])[2]/following::select[1]</value>
      <webElementGuid>e8fcfcf8-bd73-4a53-a5b2-7ec95a9ce4ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temperatura:'])[3]/preceding::select[1]</value>
      <webElementGuid>ed3d9b6b-43a6-4895-9a90-10e868d54fb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sociedad Argentina de Patología. 2022.'])[1]/preceding::select[2]</value>
      <webElementGuid>5755bae7-c466-4475-9b5c-fcc9e06154f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[7]/select</value>
      <webElementGuid>3048d76f-b56b-4882-8b50-176c7e2ac17d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'chromogenIncubation' and @name = 'chromogenIncubation' and (text() = '-- Seleccione un tiempo --15 min30 min60 minOvernightOtro' or . = '-- Seleccione un tiempo --15 min30 min60 minOvernightOtro')]</value>
      <webElementGuid>68c35bf7-2e16-4e1f-8d48-c747d4161843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='antigenicRetrievalTime']</value>
      <webElementGuid>5687eaa7-a723-4416-95ee-f7f722c55e49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/form/div[2]/div[9]/select</value>
      <webElementGuid>7f012da0-040e-4534-b22d-81b1940650c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiempo:'])[1]/following::select[1]</value>
      <webElementGuid>f54fa53f-71ba-4e61-af18-1716b2505bd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buffer:'])[1]/following::select[1]</value>
      <webElementGuid>fd5c7ec7-e3d6-4976-ad32-bf8a7220b020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temperatura:'])[2]/preceding::select[1]</value>
      <webElementGuid>a2df8421-ad50-47b2-9f1b-38c8058bf27e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sistema de Visualización'])[1]/preceding::select[2]</value>
      <webElementGuid>f6d3d49a-39a4-4163-85d7-b902f1de6dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/select</value>
      <webElementGuid>5b6733e7-28a9-4617-9c0f-2015e09bfbde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'antigenicRetrievalTime' and @name = 'antigenicRetrievalTime' and (text() = '-- Seleccione un tiempo --15 min30 min60 minOvernightOtro' or . = '-- Seleccione un tiempo --15 min30 min60 minOvernightOtro')]</value>
      <webElementGuid>dd164683-608e-408c-9b93-2126882ac1d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
