<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Seleccione la temperatura --0C5C1_fedc78_1_2</name>
   <tag></tag>
   <elementGuidId>c43cbe78-127c-42c2-8e7c-b9d6dbe710ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='visualizationSystemIncubation']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#visualizationSystemIncubation</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>aaa67f60-5d79-426d-9c76-5227cc65583e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>6b3e79e8-f116-41dc-a784-9c0be5e52f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>visualizationSystemIncubation</value>
      <webElementGuid>a6ba20b2-d56e-44dd-acb9-ff5eb2858ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>visualizationSystemIncubation</value>
      <webElementGuid>5202918f-89fe-4d80-a894-ac8ac1a6af8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Seleccione la temperatura --0°C5°C10°C15°C20°C25°C30°C35°C40°C45°C50°C55°C60°C65°C70°C75°C80°C85°C90°C95°C100°C</value>
      <webElementGuid>990594e2-b96f-4424-8328-b4967a77914c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;visualizationSystemIncubation&quot;)</value>
      <webElementGuid>9fd8288d-eaee-4af8-aad7-da4ddddf0f68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>020f757b-3699-4fb4-930f-e7f68f2fe20c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>b60fdb11-0f8e-4287-b873-b553bc10170f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>visualizationSystemIncubation</value>
      <webElementGuid>fde81f8b-94e5-4954-a7ba-90db281beb92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>visualizationSystemIncubation</value>
      <webElementGuid>76455875-6e52-4d63-ac48-074af4e49261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Seleccione la temperatura --0°C5°C10°C15°C20°C25°C30°C35°C40°C45°C50°C55°C60°C65°C70°C75°C80°C85°C90°C95°C100°C</value>
      <webElementGuid>3d494790-6686-4262-96f5-0814cefb801a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;visualizationSystemIncubation&quot;)</value>
      <webElementGuid>b03c9d7e-5832-4e7b-8521-0afec646bfbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='visualizationSystemIncubation']</value>
      <webElementGuid>d953b993-18a7-4246-b030-5463874e0a43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/form/div[3]/div[4]/select</value>
      <webElementGuid>4dde353e-c618-4a5e-90fe-252950bebb20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temperatura de incubación:'])[1]/following::select[1]</value>
      <webElementGuid>2638924c-6af6-4956-bba1-06c4dc893916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiempo de incubación:'])[2]/following::select[2]</value>
      <webElementGuid>e34abd83-fa4a-4332-9c08-fb2e9a8e57c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cromógeno'])[1]/preceding::select[1]</value>
      <webElementGuid>83c4a016-88fb-4f7a-8f00-133b291f4125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marca:'])[3]/preceding::select[1]</value>
      <webElementGuid>3ad659c9-fdf3-49a3-bf91-79befb7f7fa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[4]/select</value>
      <webElementGuid>b1aeb696-16da-4b98-b9e6-3d19d78abdec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'visualizationSystemIncubation' and @name = 'visualizationSystemIncubation' and (text() = '-- Seleccione la temperatura --0°C5°C10°C15°C20°C25°C30°C35°C40°C45°C50°C55°C60°C65°C70°C75°C80°C85°C90°C95°C100°C' or . = '-- Seleccione la temperatura --0°C5°C10°C15°C20°C25°C30°C35°C40°C45°C50°C55°C60°C65°C70°C75°C80°C85°C90°C95°C100°C')]</value>
      <webElementGuid>aee13375-5173-4a26-ab64-fdb4debdb188</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
