<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Seleccione un tiempo --15 min30 m_562664_1_2_3</name>
   <tag></tag>
   <elementGuidId>d6ec5db7-4a5f-4005-a7df-057e520c6dad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#visualizationSystemTime</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='visualizationSystemTime']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ff3cfad7-e83a-4d43-bfbe-425ee5274310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>f38c27e6-98ca-46b1-bcd1-c1f038f79bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>visualizationSystemTime</value>
      <webElementGuid>3d5e2593-be8b-4194-8879-6ee338bd5ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>visualizationSystemTime</value>
      <webElementGuid>91f3a9df-9bca-4395-9fe5-95083255f098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Seleccione un tiempo --15 min30 min60 minOvernightOtro</value>
      <webElementGuid>886a7ad7-6368-4912-b713-689c917a5d01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;visualizationSystemTime&quot;)</value>
      <webElementGuid>6ebc26cd-0e61-478d-82ad-10cd88796e8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c8bfbbe7-225d-4c09-98d8-53b7e9c5194f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>f8f55ab1-f651-4004-a058-d9aaaa4e78fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chromogenIncubation</value>
      <webElementGuid>09283ce6-51bb-4d3f-aac5-4450ddaa7012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chromogenIncubation</value>
      <webElementGuid>feac81eb-c810-4820-a3c1-cdf7199ebee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Seleccione un tiempo --15 min30 min60 minOvernightOtro</value>
      <webElementGuid>d8db57bb-5977-4c3b-a08b-9619244d085c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chromogenIncubation&quot;)</value>
      <webElementGuid>1fb8f51f-02b2-4f35-9809-58777260ed6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f64c7343-19d3-4701-bfbc-9a5ccaf21e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>c863f14a-543e-4a9f-b68d-4c9e1a208533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chromogenIncubation</value>
      <webElementGuid>7819e622-6b70-439b-aa16-b30c77ee5171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chromogenIncubation</value>
      <webElementGuid>52dee896-f7ad-4f23-8762-c45d92f2c1b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Seleccione un tiempo --15 min30 min60 minOvernightOtro</value>
      <webElementGuid>11da9801-6767-4e94-bfd5-1290a0793aab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chromogenIncubation&quot;)</value>
      <webElementGuid>7b66f9b0-3c80-486d-bce7-bcf85e43b6ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='visualizationSystemTime']</value>
      <webElementGuid>a363b610-7671-49e2-bd51-1166b4ee6cce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/form/div[3]/div[3]/select</value>
      <webElementGuid>bb105d6d-f866-4ede-a3a0-1d59343488aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiempo de incubación:'])[2]/following::select[1]</value>
      <webElementGuid>78ded250-47d0-418e-afc1-3955accc278f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Producto:'])[1]/following::select[1]</value>
      <webElementGuid>3df55c49-fecb-4ed1-9a1a-ac0fb3876800</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temperatura de incubación:'])[1]/preceding::select[1]</value>
      <webElementGuid>f6cc8486-ec68-49af-ad60-0ccfd6265cbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cromógeno'])[1]/preceding::select[2]</value>
      <webElementGuid>928fbc01-e6b2-4622-b343-763ced1e393d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/select</value>
      <webElementGuid>21c8e5a4-aa53-44b5-876c-0d356931b3e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'visualizationSystemTime' and @name = 'visualizationSystemTime' and (text() = '-- Seleccione un tiempo --15 min30 min60 minOvernightOtro' or . = '-- Seleccione un tiempo --15 min30 min60 minOvernightOtro')]</value>
      <webElementGuid>cf167c62-4764-41e0-afcc-49304d50f4f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='chromogenIncubation']</value>
      <webElementGuid>606c7170-611f-4a3e-8224-0147217dec4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/form/div[3]/div[7]/select</value>
      <webElementGuid>7348e1c7-f65a-4fd1-b7af-34bf1975f6b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiempo de incubación:'])[3]/following::select[1]</value>
      <webElementGuid>5b69ab0c-b6d7-4edf-b6c9-bb07e0e0edc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Producto:'])[2]/following::select[1]</value>
      <webElementGuid>ebad5054-c19d-4307-a348-f4db285b27ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temperatura:'])[3]/preceding::select[1]</value>
      <webElementGuid>5ccbc60a-00ad-43ca-b954-223987674e8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sociedad Argentina de Patología. 2022.'])[1]/preceding::select[2]</value>
      <webElementGuid>84dec2da-22ab-4f11-8e54-53404c634615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[7]/select</value>
      <webElementGuid>39c9cd85-5608-4755-a597-1658b3291db2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'chromogenIncubation' and @name = 'chromogenIncubation' and (text() = '-- Seleccione un tiempo --15 min30 min60 minOvernightOtro' or . = '-- Seleccione un tiempo --15 min30 min60 minOvernightOtro')]</value>
      <webElementGuid>a0c9df88-d7a8-4f3f-beea-3e49e8e16576</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
