<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Seleccione un dispositivo --Autom_5028c4</name>
   <tag></tag>
   <elementGuidId>4079118c-4d6a-4749-85b9-931d0f7fa7a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#antigenicRetrievalDevice</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='antigenicRetrievalDevice']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b40ac7a5-d943-4a59-bdef-07312e7c8b36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>86620d95-cf25-4c1c-84f1-69fd4647e374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>antigenicRetrievalDevice</value>
      <webElementGuid>3242703d-0680-4119-b63c-da5709cd66da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>antigenicRetrievalDevice</value>
      <webElementGuid>ba81f248-a202-4cd8-95d8-9e9dd79d7d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Seleccione un dispositivo --AutomatizadoMicroondasOlla a presiónBaño térmicoOtro</value>
      <webElementGuid>cb128883-6784-4d38-88ab-1f72d5954dfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;antigenicRetrievalDevice&quot;)</value>
      <webElementGuid>7c72ea1a-32a1-4851-afe7-83d59eec0e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7046d878-9f38-4f5e-ae94-aba2e8bbb5dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>07db4e8f-b80b-4a48-801f-5eeb1bb13b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>antigenicRetrievalDevice</value>
      <webElementGuid>ef2950b9-804d-454e-9c1c-dd3bd5bcb3a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>antigenicRetrievalDevice</value>
      <webElementGuid>6f78b1d5-4418-4915-853b-b157ff582425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Seleccione un dispositivo --AutomatizadoMicroondasOlla a presiónBaño térmicoOtro</value>
      <webElementGuid>577d6f74-dfa6-44c4-af77-6e5b44e693fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;antigenicRetrievalDevice&quot;)</value>
      <webElementGuid>9ddcb493-c4fc-474a-a432-ad700a2dad28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6c5b721e-813b-4d23-bbe8-58b5555d6b11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>e1bf6993-2318-466f-8cbf-1eece6b0557c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>antigenicRetrievalDevice</value>
      <webElementGuid>a13f52f4-ed81-4ac4-9fb1-11387f4077b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>antigenicRetrievalDevice</value>
      <webElementGuid>4aad26c0-a7f2-4e1a-8b49-6b46da574a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Seleccione un dispositivo --AutomatizadoMicroondasOlla a presiónBaño térmicoOtro</value>
      <webElementGuid>81c396dd-b560-4ce7-827f-baba9f825ae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;antigenicRetrievalDevice&quot;)</value>
      <webElementGuid>2cf79ef6-b066-4096-88f4-436731cf02db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='antigenicRetrievalDevice']</value>
      <webElementGuid>b180b937-838d-4164-9448-07192581365e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/form/div[2]/div[7]/select</value>
      <webElementGuid>b0d5e7c8-667a-4021-8ef0-00eddfdaf22a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dispositivo:'])[1]/following::select[1]</value>
      <webElementGuid>d8c5df7f-a11c-4ed8-9fe4-0ecbf6660fa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recuperación Antigénica'])[1]/following::select[1]</value>
      <webElementGuid>1ce191d6-afa1-4c21-a133-ec8df4733028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buffer:'])[1]/preceding::select[1]</value>
      <webElementGuid>b4d5bf7a-087b-4a82-9999-bc9509e85bc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiempo:'])[1]/preceding::select[1]</value>
      <webElementGuid>1d1b8b05-cbfa-4c8a-a8e0-b3196978ecce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/select</value>
      <webElementGuid>1b6db2bb-8663-4b94-8bc6-2ed2a3e0cf24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'antigenicRetrievalDevice' and @name = 'antigenicRetrievalDevice' and (text() = '-- Seleccione un dispositivo --AutomatizadoMicroondasOlla a presiónBaño térmicoOtro' or . = '-- Seleccione un dispositivo --AutomatizadoMicroondasOlla a presiónBaño térmicoOtro')]</value>
      <webElementGuid>b32a9e54-6ee9-4481-b06c-0d084bab020e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
