<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Seleccione la temperatura --0C5C1_fedc78</name>
   <tag></tag>
   <elementGuidId>08a903fa-d2d9-4b34-995e-edaa0aa78da1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#primaryAntigenTemperature</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='primaryAntigenTemperature']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6de080e6-8a45-422d-ba6a-1574319b7d44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>50dc3263-b922-4cd3-9b9d-61fba7f2ef63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>primaryAntigenTemperature</value>
      <webElementGuid>2a838d4a-c829-4063-ba9c-2efa31e8b284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>primaryAntigenTemperature</value>
      <webElementGuid>bc9764b1-f5ac-4915-b97c-af58ff14417a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Seleccione la temperatura --0°C5°C10°C15°C20°C25°C30°C35°C40°C45°C50°C55°C60°C65°C70°C75°C80°C85°C90°C95°C100°C</value>
      <webElementGuid>3348c5eb-feee-40a1-84a4-cb12360aa18e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;primaryAntigenTemperature&quot;)</value>
      <webElementGuid>904fe67a-a742-4c78-8ca6-f1ac887d45d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>79c91c2f-be2a-4cab-b74b-af15416d267f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>f8070556-4ee8-482a-ae53-9bd415635b82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>primaryAntigenTemperature</value>
      <webElementGuid>4be92df3-3bb9-493c-8b5a-d3c718810eed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>primaryAntigenTemperature</value>
      <webElementGuid>a7833882-3cb9-467c-aa43-a8d7c790a69f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Seleccione la temperatura --0°C5°C10°C15°C20°C25°C30°C35°C40°C45°C50°C55°C60°C65°C70°C75°C80°C85°C90°C95°C100°C</value>
      <webElementGuid>5586b0a8-8252-4695-8702-5ab42fb45eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;primaryAntigenTemperature&quot;)</value>
      <webElementGuid>1c665bd3-957e-4cbd-bd4a-c80129cb1aea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>202fc3b8-b310-4bb1-a4ac-a848bf19aad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>fd34b40d-8ce6-4f73-b650-e4283513b11f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>primaryAntigenTemperature</value>
      <webElementGuid>002c0d80-0d7a-4138-af21-9ec4912e60d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>primaryAntigenTemperature</value>
      <webElementGuid>000a53c2-949c-4d5b-8598-4d06761574c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Seleccione la temperatura --0°C5°C10°C15°C20°C25°C30°C35°C40°C45°C50°C55°C60°C65°C70°C75°C80°C85°C90°C95°C100°C</value>
      <webElementGuid>f49857ee-c07f-4042-9a72-1817a16f77d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;primaryAntigenTemperature&quot;)</value>
      <webElementGuid>a788c610-93b5-4415-a7cc-e7c552e86255</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='primaryAntigenTemperature']</value>
      <webElementGuid>2a794b4c-39a8-4650-9668-57bf4e350d92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/form/div[2]/div[6]/select</value>
      <webElementGuid>9d1a6af5-ca48-4a23-afbe-5ef42d64f640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temperatura:'])[1]/following::select[1]</value>
      <webElementGuid>567e0eec-c3d2-4888-bcfa-0309c8004823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiempo de incubación:'])[1]/following::select[2]</value>
      <webElementGuid>3db52e48-9040-4c1a-aeb7-d3cae5e76ab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recuperación Antigénica'])[1]/preceding::select[1]</value>
      <webElementGuid>7154bac9-052e-4f81-a446-ca5efdf1c31e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dispositivo:'])[1]/preceding::select[1]</value>
      <webElementGuid>50a975ca-a2bd-438c-9964-b6ec0d382cde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/select</value>
      <webElementGuid>ff097a9d-d6e0-4236-aff5-ae92c03dad68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'primaryAntigenTemperature' and @name = 'primaryAntigenTemperature' and (text() = '-- Seleccione la temperatura --0°C5°C10°C15°C20°C25°C30°C35°C40°C45°C50°C55°C60°C65°C70°C75°C80°C85°C90°C95°C100°C' or . = '-- Seleccione la temperatura --0°C5°C10°C15°C20°C25°C30°C35°C40°C45°C50°C55°C60°C65°C70°C75°C80°C85°C90°C95°C100°C')]</value>
      <webElementGuid>6b97dd28-593f-47f7-8313-7e8dfc86bee3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
