<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Seleccione una marca --DAKO - AGI_de3eda_1</name>
   <tag></tag>
   <elementGuidId>03d8a68d-dfbd-4ded-847b-36b4e73157e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='visualizationSystemBrand']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#visualizationSystemBrand</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b0938ee2-ad20-41d1-8aec-4a390979abb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>e069a0d9-3c9a-46a2-ae26-797e62997ad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>visualizationSystemBrand</value>
      <webElementGuid>5cf3854e-24c4-44cf-98d4-9a51c5ae7aeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>visualizationSystemBrand</value>
      <webElementGuid>258d98ab-20aa-4301-beed-0611c246db73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Seleccione una marca --DAKO - AGILENTVENTANALEICACELLMARQUEBIOSBBIOGENEXVECTOR</value>
      <webElementGuid>ad377564-242d-4d22-9d34-e8dba34f3979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;visualizationSystemBrand&quot;)</value>
      <webElementGuid>8f4ae6fb-4510-4636-ada2-d2ce16f5dcd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a75d11fe-01d2-4994-8e1c-39da6429885b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>07199017-0077-4e01-b224-7371d99e6145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>visualizationSystemBrand</value>
      <webElementGuid>70b69c15-b77e-47d4-a41b-640d880b1190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>visualizationSystemBrand</value>
      <webElementGuid>f75ab1c2-4fdc-4754-a7cd-a74d9ec8cb2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Seleccione una marca --DAKO - AGILENTVENTANALEICACELLMARQUEBIOSBBIOGENEXVECTOR</value>
      <webElementGuid>eaa279e6-07cc-48f2-ad35-762b6c25d53b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;visualizationSystemBrand&quot;)</value>
      <webElementGuid>cffdafad-7fd6-4f44-bdaf-59f8ea2a5a3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='visualizationSystemBrand']</value>
      <webElementGuid>8ec8546f-46fa-4559-be62-cc796a8b547b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/form/div[3]/div/select</value>
      <webElementGuid>22d02993-fa9c-4063-9f8d-511e5eb557d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marca:'])[2]/following::select[1]</value>
      <webElementGuid>1942fcab-1eef-4a1e-b1ec-192aa499b944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sistema de Visualización'])[1]/following::select[1]</value>
      <webElementGuid>07c44de8-79df-47df-b536-93c3ab5dfbe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Producto:'])[1]/preceding::select[1]</value>
      <webElementGuid>7d4539b8-4dc4-484b-ad4c-6ddda2c35a74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiempo de incubación:'])[2]/preceding::select[1]</value>
      <webElementGuid>8097aac3-12ba-459f-9f2c-60104bfa12ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>4f8b535a-5b7f-4625-9fb2-8a40d00bbff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'visualizationSystemBrand' and @name = 'visualizationSystemBrand' and (text() = '-- Seleccione una marca --DAKO - AGILENTVENTANALEICACELLMARQUEBIOSBBIOGENEXVECTOR' or . = '-- Seleccione una marca --DAKO - AGILENTVENTANALEICACELLMARQUEBIOSBBIOGENEXVECTOR')]</value>
      <webElementGuid>93939fd2-258c-4266-9ea4-a46c8f1802ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
