<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Seleccione una marca --DAKO - AGI_de3eda</name>
   <tag></tag>
   <elementGuidId>64da0255-2d2e-4497-8820-49c460711adb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#primaryAntigenBrand</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='primaryAntigenBrand']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4381843f-04f3-4b73-9ca9-ca83d7a7a87d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>881b1806-6543-4d24-8fa9-c0cda15eb509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>primaryAntigenBrand</value>
      <webElementGuid>6bf44b95-4c06-4781-9673-1678a0acde65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>primaryAntigenBrand</value>
      <webElementGuid>33d24a09-8078-4fe8-80f3-e2401d348177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Seleccione una marca --DAKO - AGILENTVENTANALEICACELLMARQUEBIOSBBIOGENEXVECTOR</value>
      <webElementGuid>97351fab-3962-4362-906f-2985599829ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;primaryAntigenBrand&quot;)</value>
      <webElementGuid>2ef944df-aa23-4b19-a374-1cbf00ab0789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e63d2b43-477c-4bf2-87ba-2a66984491ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>32039613-3dfe-4bd3-958e-96821f0c3c49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>primaryAntigenBrand</value>
      <webElementGuid>33de47fb-3b5a-4ae9-a197-56e5f6b45fcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>primaryAntigenBrand</value>
      <webElementGuid>1a0048b7-f68f-46d0-a94f-a39ce86035a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Seleccione una marca --DAKO - AGILENTVENTANALEICACELLMARQUEBIOSBBIOGENEXVECTOR</value>
      <webElementGuid>39b3da83-bfcc-468d-9d15-4e7e339e981a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;primaryAntigenBrand&quot;)</value>
      <webElementGuid>a444ba6e-3183-4e02-b849-624cc9dff36a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f4f5eadd-f987-4ac0-94e3-f3c17d173a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>bea2d9c3-e5c3-4ba7-b61f-eb2389248fab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>primaryAntigenBrand</value>
      <webElementGuid>b161bdfc-a5c6-47d0-9042-63060b2d0520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>primaryAntigenBrand</value>
      <webElementGuid>b1fe26ea-1718-48b6-9e45-75e1bbbe7d1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Seleccione una marca --DAKO - AGILENTVENTANALEICACELLMARQUEBIOSBBIOGENEXVECTOR</value>
      <webElementGuid>b77983b1-e0fb-4e8d-a38d-503eec66a236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;primaryAntigenBrand&quot;)</value>
      <webElementGuid>17c782ef-0b33-4488-aad4-81f46fca39ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='primaryAntigenBrand']</value>
      <webElementGuid>573bf652-192f-4888-8717-15b582133fb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/form/div[2]/div[3]/select</value>
      <webElementGuid>0ff2e6c5-47c6-4feb-b459-3524bca7a549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marca:'])[1]/following::select[1]</value>
      <webElementGuid>5f87c9b3-3689-42a1-a4dc-a71d8ca1c202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clon:'])[1]/following::select[2]</value>
      <webElementGuid>8568ddcb-0b44-4ff9-b03f-848f300e2f48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dilución:'])[1]/preceding::select[1]</value>
      <webElementGuid>ee8a631d-04ba-4429-9608-27677e501a2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiempo de incubación:'])[1]/preceding::select[2]</value>
      <webElementGuid>07ccf888-bf31-4af1-aff0-2e52d5400210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>38d19ed2-3c8a-4f95-8ef0-ba2464c9f517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'primaryAntigenBrand' and @name = 'primaryAntigenBrand' and (text() = '-- Seleccione una marca --DAKO - AGILENTVENTANALEICACELLMARQUEBIOSBBIOGENEXVECTOR' or . = '-- Seleccione una marca --DAKO - AGILENTVENTANALEICACELLMARQUEBIOSBBIOGENEXVECTOR')]</value>
      <webElementGuid>49ad0869-b0b5-4fbf-88ea-c4da5bb97b61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
