<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Seleccione la temperatura --0C5C1_fedc78_1_2_3</name>
   <tag></tag>
   <elementGuidId>62acb62f-20ba-4209-9f08-b7ce62543172</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='chromogenTemperature']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#chromogenTemperature</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7213bde5-f69a-41cd-b03d-9241cce6f48a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>98c4c6fb-e949-4385-bc54-803ff58d280f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chromogenTemperature</value>
      <webElementGuid>a47f58ba-0e70-4446-8dcb-2f37d332f015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chromogenTemperature</value>
      <webElementGuid>bcfe173a-ea64-48bd-8435-24d1b587a3e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Seleccione la temperatura --0°C5°C10°C15°C20°C25°C30°C35°C40°C45°C50°C55°C60°C65°C70°C75°C80°C85°C90°C95°C100°C</value>
      <webElementGuid>425578be-584a-44da-bf53-86a5c127c8cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chromogenTemperature&quot;)</value>
      <webElementGuid>bf1e8088-6224-4c73-a11b-fa1ca68ed660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5b2a0dec-85a6-4e22-8e5a-0d2886927fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>ac28b5c8-c6cc-486b-92ac-ef251b83dcb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chromogenTemperature</value>
      <webElementGuid>0c5b692d-ef53-4c66-ace3-89df2df30ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chromogenTemperature</value>
      <webElementGuid>88e6e7bd-cbd4-4be4-b19c-d91b68c0f4eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Seleccione la temperatura --0°C5°C10°C15°C20°C25°C30°C35°C40°C45°C50°C55°C60°C65°C70°C75°C80°C85°C90°C95°C100°C</value>
      <webElementGuid>37c46649-b914-428b-87c5-d654b6c776b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chromogenTemperature&quot;)</value>
      <webElementGuid>00c2140b-425b-4fdb-80ed-acea8315e136</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='chromogenTemperature']</value>
      <webElementGuid>79745a2c-75d6-4592-ae92-141d05bc7f28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/form/div[3]/div[8]/select</value>
      <webElementGuid>be168bd3-8d4e-43d9-a898-035f4b7b0ab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temperatura:'])[3]/following::select[1]</value>
      <webElementGuid>db925efc-cde0-480b-813f-f740a587d118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiempo de incubación:'])[3]/following::select[2]</value>
      <webElementGuid>97d5606e-dabd-42a0-9b36-8c37dd0b3ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sociedad Argentina de Patología. 2022.'])[1]/preceding::select[1]</value>
      <webElementGuid>c2822fa4-3659-4510-8b79-b34e19473bc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='calidadsap@patología.org.ar'])[1]/preceding::select[1]</value>
      <webElementGuid>d3bb8d6e-43b6-4a32-9500-06af5273331f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/select</value>
      <webElementGuid>3d5af185-e070-415a-9631-3fd3f416f0ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'chromogenTemperature' and @name = 'chromogenTemperature' and (text() = '-- Seleccione la temperatura --0°C5°C10°C15°C20°C25°C30°C35°C40°C45°C50°C55°C60°C65°C70°C75°C80°C85°C90°C95°C100°C' or . = '-- Seleccione la temperatura --0°C5°C10°C15°C20°C25°C30°C35°C40°C45°C50°C55°C60°C65°C70°C75°C80°C85°C90°C95°C100°C')]</value>
      <webElementGuid>3303e6ce-ee46-4d21-b5af-363bf286f510</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
