<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Seleccione un clon --SP1EP16F11EP220Otro</name>
   <tag></tag>
   <elementGuidId>5263af25-4ce1-4956-aff5-153d3b6b987f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#primaryAntigenClon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='primaryAntigenClon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6a74934f-09a9-4f2b-a3b3-d36cacc1fee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>b66782c8-8fcb-49da-b9a1-c759b5801ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>primaryAntigenClon</value>
      <webElementGuid>46f84968-3f4e-4984-8662-abda1d7f7956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>primaryAntigenClon</value>
      <webElementGuid>a1a90d25-f472-48fc-8d64-7d0d9b7aa090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Seleccione un clon --SP1EP16F11EP220Otro</value>
      <webElementGuid>cb31aca2-68a8-44f7-ad36-8d9883dff805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;primaryAntigenClon&quot;)</value>
      <webElementGuid>c1084a95-bc00-47da-9a39-53a2c2f574c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>38925ad8-f639-4537-981a-5fcf34d7e647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>8e1be003-90e5-401f-bfd9-bb1084f1dd43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>primaryAntigenClon</value>
      <webElementGuid>8bc3534b-8a24-4c92-8b6d-97a48123bbe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>primaryAntigenClon</value>
      <webElementGuid>42e11ef7-887f-4891-8fcf-c94cb2c312a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Seleccione un clon --SP1EP16F11EP220Otro</value>
      <webElementGuid>a26fecd1-a595-40b3-8c75-5fecba3ea7d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;primaryAntigenClon&quot;)</value>
      <webElementGuid>f03b5893-c10d-45ce-8fce-e7a3f0931350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d82d11fe-976f-4758-87b5-1266d4b99b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>9f7d43a2-33a9-46cd-892d-56c6de84fdcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>primaryAntigenClon</value>
      <webElementGuid>bfd76c32-3e91-4bef-bd4c-c8ffb636f464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>primaryAntigenClon</value>
      <webElementGuid>7ae7d797-b825-4747-bce1-02d1b24a749b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Seleccione un clon --SP1EP16F11EP220Otro</value>
      <webElementGuid>b094534b-75f7-41c3-8066-6211f6997877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;primaryAntigenClon&quot;)</value>
      <webElementGuid>be30f880-4c82-43a2-8897-a32952d1048e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='primaryAntigenClon']</value>
      <webElementGuid>898d18a6-2357-414d-bee7-39311f373f76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/form/div[2]/div[2]/select</value>
      <webElementGuid>80d64f50-6fc4-4995-a3c6-20fd6b3cd6fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clon:'])[1]/following::select[1]</value>
      <webElementGuid>543e96a3-6538-489e-a944-79005534b28e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anticuerpo Primario'])[1]/following::select[1]</value>
      <webElementGuid>2e678996-5128-468c-bbfa-e5fcb83f33f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marca:'])[1]/preceding::select[1]</value>
      <webElementGuid>d32f1fcb-8992-4fa2-9ee3-1b3dc73b0735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dilución:'])[1]/preceding::select[2]</value>
      <webElementGuid>db3054e6-ce3a-4735-a341-c849fcf9913a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>501c9dea-fa20-4f89-8963-eb82b2e05228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'primaryAntigenClon' and @name = 'primaryAntigenClon' and (text() = '-- Seleccione un clon --SP1EP16F11EP220Otro' or . = '-- Seleccione un clon --SP1EP16F11EP220Otro')]</value>
      <webElementGuid>ff624cac-1f01-4f11-b6bf-72595012c887</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
