<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Seleccione un tipo --ManualAut. V_30d2ad</name>
   <tag></tag>
   <elementGuidId>1008fe69-2268-4e61-b43c-52b6f3fb1865</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#immunohistochemistryType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='immunohistochemistryType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4bcb3ec0-d8cd-44be-a661-f155119212a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>d419cef6-de8c-446d-99d5-464c9a88d502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>immunohistochemistryType</value>
      <webElementGuid>a4bb3ab1-fd2e-40a4-92df-8e54de9a00f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>immunohistochemistryType</value>
      <webElementGuid>fca9d42c-2e9c-4849-b36f-25ce2563ac79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Seleccione un tipo --ManualAut. VentanaAut. DAKO / AgilentAut. LEICAOtros</value>
      <webElementGuid>0bac2fd2-0fb1-497c-b4c5-25b56f65536a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;immunohistochemistryType&quot;)</value>
      <webElementGuid>34db4ff4-a83a-4737-bee4-65f11fab88aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bd5105de-ead2-46e7-8278-59822309edda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>10fa761f-98cd-44b3-a18e-97b0eb0f4932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>immunohistochemistryType</value>
      <webElementGuid>732903e1-bdef-4f19-84b7-2bc83326c8d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>immunohistochemistryType</value>
      <webElementGuid>7f2006e2-ca6b-4737-be55-4860672e728f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Seleccione un tipo --ManualAut. VentanaAut. DAKO / AgilentAut. LEICAOtros</value>
      <webElementGuid>7a251b77-2b21-48fe-8ee3-295820da211f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;immunohistochemistryType&quot;)</value>
      <webElementGuid>9d8e6b12-c646-40bf-80d1-3974b035024d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>72d106f6-31e9-45d1-80e4-3fe36fee80d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>0ab29a74-20c2-4f17-a189-93a222186647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>immunohistochemistryType</value>
      <webElementGuid>02ffc99c-9e37-436c-aaa3-64ba88a4c4c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>immunohistochemistryType</value>
      <webElementGuid>9c420c9d-1dbf-4a4d-935c-bad4490340f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Seleccione un tipo --ManualAut. VentanaAut. DAKO / AgilentAut. LEICAOtros</value>
      <webElementGuid>c51bb5cf-e70c-4b1a-a45d-681a285c2797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;immunohistochemistryType&quot;)</value>
      <webElementGuid>3872702e-2a46-4012-a682-5668ca965258</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='immunohistochemistryType']</value>
      <webElementGuid>d0d85b8d-fc62-4d1e-a4b8-b088f960ebe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/form/div[2]/div/select</value>
      <webElementGuid>b8c941e3-8d9b-489b-a4af-6bccab4f7549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo:'])[1]/following::select[1]</value>
      <webElementGuid>4a4db038-d0a2-450b-a1c4-d58dfe48e768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Técnica de Inmunohistoquímica'])[1]/following::select[1]</value>
      <webElementGuid>c4aa358b-224a-4d3f-b4c7-1ff120453f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anticuerpo Primario'])[1]/preceding::select[1]</value>
      <webElementGuid>92979902-1b89-44b6-8053-ad6786562fc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clon:'])[1]/preceding::select[1]</value>
      <webElementGuid>82a68c98-7fbb-4057-86d4-9393a700b39b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>ee561a42-3e91-497c-b90e-a64318fc92d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'immunohistochemistryType' and @name = 'immunohistochemistryType' and (text() = '-- Seleccione un tipo --ManualAut. VentanaAut. DAKO / AgilentAut. LEICAOtros' or . = '-- Seleccione un tipo --ManualAut. VentanaAut. DAKO / AgilentAut. LEICAOtros')]</value>
      <webElementGuid>45794e3c-244c-4ee0-9b7e-18c83ce3251e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
