<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Seleccione un tiempo --15 min30 m_562664_1_2</name>
   <tag></tag>
   <elementGuidId>a59944f6-ca16-4b4f-a4ea-289c537e71cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#antigenicRetrievalTime</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='antigenicRetrievalTime']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3cabb896-a238-4bdb-b381-d2cbf4014e65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>7e318539-22ea-4aee-9bde-bcae9e1f63b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>antigenicRetrievalTime</value>
      <webElementGuid>c2ea79bc-fb58-4500-8473-f6acd81b2a91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>antigenicRetrievalTime</value>
      <webElementGuid>9f8774e8-939b-4cac-8694-937ac267029d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Seleccione un tiempo --15 min30 min60 minOvernightOtro</value>
      <webElementGuid>c4c6af69-86d0-47dd-a413-67f90f99c836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;antigenicRetrievalTime&quot;)</value>
      <webElementGuid>165c8a08-5e5c-42ce-bb4b-10e5da907915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>429c3d4b-d9b5-4ef2-92f4-bc3d826f6fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>e0fa6c1d-b051-4101-91c8-13c5536b9f6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>visualizationSystemTime</value>
      <webElementGuid>05635e6b-1b2c-4827-81ed-8c43cfb53441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>visualizationSystemTime</value>
      <webElementGuid>12508617-bcec-4214-a874-80ca00df69c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Seleccione un tiempo --15 min30 min60 minOvernightOtro</value>
      <webElementGuid>1186cdba-6997-4653-a43c-f57e9fc48c76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;visualizationSystemTime&quot;)</value>
      <webElementGuid>5394217b-4330-46b1-a8e5-702c49b60b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b46ed5d2-7755-46b6-84d5-52fb74b00ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>39b184d4-99c2-4e36-bc3f-ca9c707a839f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>visualizationSystemTime</value>
      <webElementGuid>a3ea47fc-11d3-47bf-a1b7-c009b29f9530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>visualizationSystemTime</value>
      <webElementGuid>22eceb7d-6c06-4fdd-b526-e43e614731c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Seleccione un tiempo --15 min30 min60 minOvernightOtro</value>
      <webElementGuid>0eb0e1f8-c889-49bd-b0c8-9a3fe85bd1a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;visualizationSystemTime&quot;)</value>
      <webElementGuid>b674a63d-77cf-4d43-b390-9b4b918cd20e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='antigenicRetrievalTime']</value>
      <webElementGuid>7e07a590-12ba-4be3-a677-2c7817b8f8ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/form/div[2]/div[9]/select</value>
      <webElementGuid>f1bbce18-bd23-44e0-a4a7-dd348c7b114e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiempo:'])[1]/following::select[1]</value>
      <webElementGuid>f068e3e8-0f4d-4bfa-a41d-d2052508d9c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buffer:'])[1]/following::select[1]</value>
      <webElementGuid>ad988b3e-d84b-4f53-9185-b414e840beb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temperatura:'])[2]/preceding::select[1]</value>
      <webElementGuid>6c7fa9ac-8f17-4256-b9e5-34658680820d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sistema de Visualización'])[1]/preceding::select[2]</value>
      <webElementGuid>52680c66-0c5d-448f-a2e4-e1e9322942c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/select</value>
      <webElementGuid>9e138dad-ccc5-48b4-a321-245de840c833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'antigenicRetrievalTime' and @name = 'antigenicRetrievalTime' and (text() = '-- Seleccione un tiempo --15 min30 min60 minOvernightOtro' or . = '-- Seleccione un tiempo --15 min30 min60 minOvernightOtro')]</value>
      <webElementGuid>9d6f3ade-248f-447a-89f0-f4da86c342fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='visualizationSystemTime']</value>
      <webElementGuid>9bc5ce02-ebbf-4eaa-a9e5-597d10232ae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/form/div[3]/div[3]/select</value>
      <webElementGuid>468f7009-381e-4007-a433-087b70cb438d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiempo de incubación:'])[2]/following::select[1]</value>
      <webElementGuid>67c56094-9bcc-4898-a4d8-972569640771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Producto:'])[1]/following::select[1]</value>
      <webElementGuid>b92cd56c-7e34-419f-bb02-5d200cd8b591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temperatura de incubación:'])[1]/preceding::select[1]</value>
      <webElementGuid>b25a440f-344f-4deb-b40d-5f1c41f8daf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cromógeno'])[1]/preceding::select[2]</value>
      <webElementGuid>51fbfed1-62b1-4d3e-9827-e23669441223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/select</value>
      <webElementGuid>384eabe8-828a-40e9-966d-d1258fdb1262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'visualizationSystemTime' and @name = 'visualizationSystemTime' and (text() = '-- Seleccione un tiempo --15 min30 min60 minOvernightOtro' or . = '-- Seleccione un tiempo --15 min30 min60 minOvernightOtro')]</value>
      <webElementGuid>f1f2571b-5f8f-4131-95d7-dfe588272d12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
