<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Nuevo Calendario</name>
   <tag></tag>
   <elementGuidId>60e66d19-0d04-461f-935b-37b40d080001</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-secondary.pointer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button' and contains(text(),'Nuevo Calendario')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d7bae246-2829-409a-9fdf-279b9467b2f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary pointer</value>
      <webElementGuid>d4803e54-fb76-4f49-bece-4aa59eb03fda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c011af80-4471-4bf9-9d60-8236fc084c09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nuevo Calendario</value>
      <webElementGuid>5e9f2411-f006-4a73-89ea-4d444c6eabab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;backoffice-screen&quot;]/div[@class=&quot;page-title&quot;]/div[@class=&quot;camp-form btn-form-size&quot;]/button[@class=&quot;btn btn-secondary pointer&quot;]</value>
      <webElementGuid>f24251f8-b79e-4ffe-9f3f-0f9f3ab3bdc8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>260d3c74-f2b9-4e1e-96d8-d172a1108ace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/button</value>
      <webElementGuid>e97ed5f3-b0d4-4c6b-9e01-fb586163cd46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calendarios'])[1]/following::button[1]</value>
      <webElementGuid>11bb407b-71b6-481e-bd94-b86749540ade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calificación'])[1]/following::button[1]</value>
      <webElementGuid>17f5ff3b-1dd4-4f5b-ba91-485ee7699e49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Corrida'])[1]/preceding::button[1]</value>
      <webElementGuid>f2bbf7cb-c8c0-4959-b458-74d92c0ad89b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Protocolo'])[1]/preceding::button[1]</value>
      <webElementGuid>333d214c-ac97-4e17-ba90-cc4b061d73d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nuevo Calendario']/parent::*</value>
      <webElementGuid>85705887-9d56-4ae9-b448-1efcf0bc52f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>fa235cb3-83ef-460e-a4c6-63c3208a9fb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Nuevo Calendario' or . = 'Nuevo Calendario')]</value>
      <webElementGuid>376b93a1-1c4e-477f-a807-0a17a11c3a44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
