<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_nombreCorrida</name>
   <tag></tag>
   <elementGuidId>553dabbf-38b4-425a-bff0-7afef22a1adc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#calendarName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text' and ..//label[contains(text(),'Nombre corrida')]]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2f272fff-6bb1-4fa6-a892-50da795449f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ec7fe1e7-c404-4f30-9135-8bcdf7c421be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>calendarName</value>
      <webElementGuid>a8bf468a-335a-4621-ab4b-e4de452cebdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>calendarName</value>
      <webElementGuid>b976fabf-fd3f-449b-b149-3f7b9fddd62c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingrese nombre corrida</value>
      <webElementGuid>88daa779-d44e-4bd8-a80e-6dffdfb9f4eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calendarName&quot;)</value>
      <webElementGuid>72651990-298c-4d4d-8fd4-147603aa0f8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='calendarName']</value>
      <webElementGuid>2f7d2d42-5cdc-4457-ba0f-32500b41990a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/div/form/div/input</value>
      <webElementGuid>e613161a-2bbf-4300-80de-4bd3ee815596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>bf14f24d-4d73-4678-9d89-2530b36e7d79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'calendarName' and @name = 'calendarName' and @placeholder = 'Ingrese nombre corrida']</value>
      <webElementGuid>8161eb2c-6ac8-4b41-8d64-a65abd904dba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
