<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Protocolo</name>
   <tag></tag>
   <elementGuidId>aa180ecb-2ef8-481f-9a8b-16aa4d4139d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#moduleId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id=&quot;moduleId&quot; and ..//label[contains(text(),'Protocolo')]]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e8ce9265-4d7f-4c6c-a906-77bfd4763856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>f3ed297f-9ca1-427a-966c-f9f9f17bc903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>moduleId</value>
      <webElementGuid>1ae6262c-d6bc-441e-97b1-fd0748b1d0cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>moduleId</value>
      <webElementGuid>49e834d5-6632-43f4-9e65-51e7ee28aab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Elija un opción --HER2RERP</value>
      <webElementGuid>2e49ba0f-5e0f-4975-a2b2-3cc6fe753315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;moduleId&quot;)</value>
      <webElementGuid>f646568d-cff6-497c-bf8e-589a710ed513</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='moduleId']</value>
      <webElementGuid>f5abf516-5cb2-427b-a5f3-78ff0160b638</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/div/form/div[2]/select</value>
      <webElementGuid>4ee5866e-ef12-4e71-b080-ad2327b94546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Protocolo:'])[1]/following::select[1]</value>
      <webElementGuid>c4c2bd32-4433-40ba-9390-ca643d0b75b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nombre corrida:'])[1]/following::select[1]</value>
      <webElementGuid>02875910-9ed5-4450-8b97-2a31501dd6c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apertura envío de protocolo:'])[1]/preceding::select[1]</value>
      <webElementGuid>cdc78c00-1d94-400f-8ff3-e18a69f74ea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clausura envío de protocolo:'])[1]/preceding::select[1]</value>
      <webElementGuid>43ad7f3e-4612-441e-bd20-9d5b99097eb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>8adfa856-fe6e-4af8-9bbf-f64c56e2aac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'moduleId' and @name = 'moduleId' and (text() = '-- Elija un opción --HER2RERP' or . = '-- Elija un opción --HER2RERP')]</value>
      <webElementGuid>03b3ab74-fab8-4b5a-8e6d-13b8def78fa9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
